import type { ToolInfo } from '../types';

export const TOOLS_LIST: ToolInfo[] = [
  {
    id: 'merge',
    title: 'Gabungkan PDF',
    description: 'Satukan beberapa file PDF menjadi satu dokumen utuh dengan urutan yang fleksibel.',
    icon: 'merge',
    category: 'organize',
    accentColor: 'from-blue-500 to-indigo-600',
    accept: '.pdf,application/pdf',
    multiple: true,
    actionText: 'Gabungkan Dokumen',
  },
  {
    id: 'split',
    title: 'Pisahkan PDF',
    description: 'Pilih dan ekstrak halaman tertentu menjadi file baru atau pisahkan menjadi file ZIP.',
    icon: 'split',
    category: 'organize',
    accentColor: 'from-indigo-500 to-purple-600',
    accept: '.pdf,application/pdf',
    multiple: false,
    actionText: 'Ekstrak Halaman',
  },
  {
    id: 'compress',
    title: 'Kompres PDF',
    description: 'Kecilkan ukuran file PDF Anda dengan pilihan preset kualitas tanpa upload ke cloud.',
    icon: 'minimize-2',
    category: 'optimize',
    accentColor: 'from-amber-500 to-orange-600',
    badge: 'Hemat Ukuran',
    accept: '.pdf,application/pdf',
    multiple: false,
    actionText: 'Kompres Sekarang',
  },
  {
    id: 'jpg-to-pdf',
    title: 'JPG ke PDF',
    description: 'Ubah gambar JPG, PNG, atau WEBP menjadi dokumen PDF berkualitas tinggi.',
    icon: 'image',
    category: 'convert',
    accentColor: 'from-emerald-500 to-teal-600',
    accept: '.jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp',
    multiple: true,
    actionText: 'Konversi ke PDF',
  },
  {
    id: 'sign',
    title: 'Tanda Tangan PDF',
    description: 'Bubuhkan tanda tangan digital Anda langsung di atas halaman PDF dengan canvas interaktif.',
    icon: 'pen-tool',
    category: 'security',
    accentColor: 'from-rose-500 to-pink-600',
    badge: 'E-Sign',
    accept: '.pdf,application/pdf',
    multiple: false,
    actionText: 'Terapkan Tanda Tangan',
  },
  {
    id: 'pdf-to-markdown',
    title: 'PDF ke Markdown',
    description: 'Ekstrak teks dan struktur dokumen PDF menjadi format Markdown (.md) untuk catatan atau AI.',
    icon: 'file-text',
    category: 'convert',
    accentColor: 'from-cyan-500 to-blue-600',
    accept: '.pdf,application/pdf',
    multiple: false,
    actionText: 'Ekstrak Markdown',
  },
  {
    id: 'word-to-pdf',
    title: 'Word ke PDF',
    description: 'Konversi file Microsoft Word (.docx) menjadi dokumen PDF secara instan di browser.',
    icon: 'file-up',
    category: 'convert',
    accentColor: 'from-sky-500 to-indigo-600',
    badge: 'Client-side',
    accept: '.docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    multiple: false,
    actionText: 'Konversi ke PDF',
  },
  {
    id: 'pdf-to-word',
    title: 'PDF ke Word (.docx)',
    description: 'Ubah teks dan konten PDF menjadi dokumen Word yang dapat diedit langsung.',
    icon: 'file-down',
    category: 'convert',
    accentColor: 'from-violet-500 to-fuchsia-600',
    badge: 'Editable',
    accept: '.pdf,application/pdf',
    multiple: false,
    actionText: 'Konversi ke Word',
  },
];
